export type LocalGithabUser ={
    "login": string,
    "id": number,
    "avatar": string,
    "name": string,
    "company": string,
    "blog": string,
    "location": string,
    "bio": string,
    "twitter": string,
    "repos": number,
    "followers": number,
    "following": number,
    "created": string,
}

export type GithabUser = { 
    "login": string,
    "id": number,
    "avatar_url": string,
    "name": string,
    "company": string,
    "blog": string,
    "location": string,
    "bio": string,
    "twitter_username": string,
    "public_repos": number,
    "followers": number,
    "following": number,
    "created_at": string,
}

export type GithubError = {
    message: string,
    documentation_url: string
}


// "login": "michey85",
// "id": 36237995,
// "node_id": "MDQ6VXNlcjM2MjM3OTk1",
// "avatar_url": "https://avatars.githubusercontent.com/u/36237995?v=4",
// "gravatar_id": "", "url": "https://api.github.com/users/michey85",
// "html_url": "https://github.com/michey85",
// "followers_url": "https://api.github.com/users/michey85/followers",
// "following_url": "https://api.github.com/users/michey85/following{/other_user}",
// "gists_url": "https://api.github.com/users/michey85/gists{/gist_id}",
// "starred_url": "https://api.github.com/users/michey85/starred{/owner}{/repo}",
// "subscriptions_url": "https://api.github.com/users/michey85/subscriptions",
// "organizations_url": "https://api.github.com/users/michey85/orgs",
// "repos_url": "https://api.github.com/users/michey85/repos",
// "events_url": "https://api.github.com/users/michey85/events{/privacy}",
// "received_events_url": "https://api.github.com/users/michey85/received_events",
// "type": "User",
// "site_admin": false,
// "name": "Mikhail Nepomniashchii",
// "company": null,
// "blog": "mishanep.com",
// "location": "Malaga",
// "email": null,
// "hireable": null,
// "bio": "React developer",
// "twitter_username": "pcgramota",
// "public_repos": 69,
// "public_gists": 0,
// "followers": 471,
// "following": 6,
// "created_at": "2018-02-07T16:18:45Z",
// "updated_at": "2023-09-22T15:45:26Z"